### PR TITLE
LWS-207: Bump dependencies

### PR DESCRIPTION
**Pull request by johanbissemattsson**
### Tickets involved
[LWS-207](https://kbse.atlassian.net/browse/LWS-207)

### Solves

Bumps dependencies

### Summary of changes

- Bump `@playwright/test` and `@axe-core/playwright`
- Bump `@floating-ui/dom`
- Bump `svelte` and sveltekit related dependencies
- Bump `tailwindcss`
- Bump `prettier`, `prettier-plugin-svelte` and `prettier-plugin-tailwindcss`
- Bump `mdsvex`
- Bump `prettier-plugin-tailwindcss` to latest
- Bump `postcss`and `postcss-import`
- Bump `autoprefixer`
- Bump `cssnano`
- Bump `husky` (and migrate to v9) and `lint-staged`
- Bump `unplugin-icons`
- Bump `typescript` and `tslib`
- Bump `vitest`
- Bump `vite`
- Bump `eslint` (and migrate to v9)

### CODE REVIEW

**Review by jesperengstrom — APPROVED** [review]
Nice work. 
Although I had to upgrade Node from 18.17.1 -> 20.14.0 to get it working.
Don't know if that has any implications on the devops side of things...

**Comment by johanbissemattsson** [comment]
> Nice work. Although I had to upgrade Node from 18.17.1 -> 20.14.0 to get it working. Don't know if that has any implications on the devops side of things...

Thanks for the heads-up regarding the Node version; I will take an extra look into the devops part!

ESLint no longer supports [Node.js < v18.18.0, v19](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/#node.js-%3C-v18.18.0%2C-v19-no-longer-supported)

**Comment by johanbissemattsson** [comment]
The node version is sadly a blocker and will have to be fixed from the devops part first.

I've added a ticket for it https://kbse.atlassian.net/browse/LWS-208

**Comment by johanbissemattsson** [comment]
A reminder: the node version in the[ github action workflow ](https://github.com/libris/lxlviewer/blob/develop/.github/workflows/lxl-web-tests.yml#L18)should also be updated when https://kbse.atlassian.net/browse/LWS-208 is resolved.

**Pull request merged**
