### PR TITLE
LXL-4485: Add date & sigel to cxz message comment

### PR DESCRIPTION
**Pull request by jesperengstrom**
## Checklist:
- [x] I have run the unit tests. `yarn test:unit`
- [ ] I have run the linter. `yarn lint`

### Tickets involved
[LXL-4485](https://kbse.atlassian.net/browse/LXL-4485)
### Solves

Pre-fill cxz comment with sigel & current date for better orientation when listing messages.

### Summary of changes

Add the template text to `language-entry` textarea on init if conditions are met: It's an empty `comment` whose mainEntity type is subclass of `AdministrativeAction`.

### CODE REVIEW

**Comment by johanbissemattsson** [comment]
I am not so familiar with CXZ but should the template also be inserted when user replies to another message by adding a comment (by pressing the plus sign)?

See attached screenshot:
 
Skärmavbild 2024-08-15 kl  13 22 06

I think it looks good to me otherwise!

**Comment by olovy** [comment]
> I am not so familiar with CXZ but should the template also be inserted when user replies to another message (by adding a comment/pressing the plus icon?)

@jesperengstrom @johanbissemattsson 
Yes, it should be inserted for every comment.
(Only for entity types `InquiryAction` and `ChangeNotice` = subclass of `AdministrativeAction`)

**Comment by jesperengstrom** [comment]
> @jesperengstrom @johanbissemattsson Yes, it should be inserted for every comment. (Only for entity types `InquiryAction` and `ChangeNotice` i.e. subclass of `AdministrativeAction`)

Ah ok. Then we need to go for a different solution, to dynamically add it to the fields. Will give it another try.

**Comment by jesperengstrom** [comment]
New try. See updated description.

**Review by olovy — APPROVED** [review]
LGTM!

The template text gets its own "step" in the undo history but I think that is fine?
We don't want to complicate this too much.

**Comment by jesperengstrom** [comment]
> The template text gets its own "step" in the undo history but I think that is fine?

Yes, maybe its fine?
We could also do `this.$refs.textarea.innerText = this.templateText` (hacky) or build an option to bypass history (complicated)

**Comment by olovy** [comment]
> > The template text gets its own "step" in the undo history but I think that is fine?
> 
> Yes, maybe it's fine? We could also do `this.$refs.textarea.innerText = this.templateText` (hacky) or build an option to bypass history (complicated)

Yes, let's merge this as is

**Pull request merged**
