### PR TITLE
Feature/lxl 4002 update lang icon

### PR DESCRIPTION
**Pull request by didair**
## Checklist:
- [x] I have run the unit tests. `yarn test:unit`
- [x] I have run the linter. `yarn lint`

## Description
Replace language icon with a new one from a different source than font-awesome

### Tickets involved
[LXL-4002](https://jira.kb.se/browse/LXL-4002)

### Solves
Replaces vague translation icon

### Summary of changes
Replaces fontawesome globe icon with a custom icon.
Adds our own icon font (assets/fonts) and imports them in icons.less)
Fixes height issue on textarea for title field

### CODE REVIEW

**Comment by didair** [comment]
Före:
Skärmavbild 2023-01-11 kl  13 10 46


Efter:
Skärmavbild 2023-01-12 kl  09 03 32

**Comment by niklasl** [comment]
Add instructions for how to maintain/add icons with a reference to, AFAICS, https://icomoon.io ? Along with appropriate attribution (MIT license) if it was from them.

**Comment by didair** [comment]
> 

Good idea. I have now updated the readme for vue-client

**Review by lrosenstrom — APPROVED** [review]
LGTM!

**Comment by didair** [comment]
@niklasl 🚢 ?

**Review by olovy — APPROVED** [review]
:ship:

**Pull request merged**
