### PR TITLE
Set button size on ReverseRelations component

### PR DESCRIPTION
**Pull request by didair**
## Checklist:
- [x] I have run the unit tests. `yarn test:unit`
- [x] I have run the linter. `yarn lint`

## Description
Fixes button alignment issues in reverse relations component

### Tickets involved
[LXL-4216](https://jira.kb.se/browse/LXL-4216)

### CODE REVIEW

**Comment by niklasl** [comment]
It's great to solve this! I only wonder why it started appearing in QA when it doesn't in PROD? What changed to make this additional style now necessary?

**Comment by didair** [comment]
@niklasl Great question! I will have a look

**Comment by didair** [comment]
The .btn class is overwriting styles from .RoundedButton in qa and not in prod. So the same issue as previously seen. How do we go about fixing this without rewriting all stylesheet?

**Comment by didair** [comment]
A better solution was to revert some changes I made last week to fix eslint errors https://github.com/libris/lxlviewer/commit/e2166c5a34e9201ab3821151ddeaaaa381c453ec and silence the warnings using eslint-disable-line. I still kept the height rule in reverse-relations so the buttons have the same height.

Skärmavbild 2023-06-27 kl  12 53 46

**Review by niklasl — APPROVED** [review]
LGTM! Nice catching of what affects the import order!

**Pull request merged**
