### PR TITLE
Feature/lxl 2744 linked work ui

### PR DESCRIPTION
**Pull request by praktwerk**
WIP

### CODE REVIEW

**Comment by praktwerk** [comment]
Tar bort WIP

**Comment by oBlissing** [comment]
Works and looks great.
One thing, is it possible (or wanted) to get the "expand/collapse all"-function to work with this as well? @mattiasbolin @praktwerk

**Comment by praktwerk** [comment]
@oBlissing oh, har helt missat den funktionen!

**Comment by praktwerk** [comment]
@oBlissing har lagt till det nu

**Pull request merged**
